# SETUP

variables:
  CURRENT_CI_IMAGE: "1"
  CI_IMAGE_DOCKER: registry.ddbuild.io/ci/dd-sdk-kotlin-multiplatform:$CURRENT_CI_IMAGE
  GIT_DEPTH: 5

  DD_SERVICE: "dd-sdk-kotlin-multiplatform"
  DD_ENV_TESTS: "ci"
  DD_CIVISIBILITY_ENABLED: "true"
  DD_INSIDE_CI: "true"
  DD_COMMON_AGENT_CONFIG: "dd.env=ci,dd.trace.enabled=false,dd.jmx.fetch.enabled=false"

stages:
  - ci-image
  - info
  - analysis
  - test

# CI IMAGE

ci-image:
  stage: ci-image
  when: manual
  except: [ tags, schedules ]
  tags: [ "arch:amd64" ]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:24.0.4-gbi-focal
  script:
    - docker buildx build --tag $CI_IMAGE_DOCKER --label target=build -f Dockerfile.gitlab --push .

env-info:
  stage: info
  when: manual
  tags: [ "macos:sonoma" ]
  allow_failure: true # do not block GH PRs
  script:
    - system_profiler SPSoftwareDataType # system info
    - xcodebuild -version
    - xcode-select -p # default Xcode
    - ls /Applications/ | grep Xcode # other Xcodes
    - xcodebuild -project sample/iosApp/iosApp.xcodeproj -scheme iosApp -showdestinations -quiet # installed iOS destinations
    - xcbeautify --version
    - swiftlint --version
    - carthage version
    - gh --version
    - brew -v
    - bundler --version
    - python3 -V
    - java --version

# Analysis

static-analysis-ios:
  stage: analysis
  tags: [ "macos:sonoma" ]
  timeout: 1h
  script:
#    - ./tools/lint/run-linter.sh
    - ./tools/license/check-license.sh

static-analysis-android:
  stage: analysis
  variables:
    DETEKT_PUBLIC_API: "false"
    DETEKT_CUSTOM_RULES_BUILD_TASK: ""
    DETEKT_CUSTOM_RULES_JAR_PATH: ""
    DETEKT_CUSTOM_RULES_YML_PATH: ""
    DETEKT_GENERATE_CLASSPATH_BUILD_TASK: "printSdkDebugRuntimeClasspath"
    DETEKT_CLASSPATH_FILE_PATH: ""
    FLAVORED_ANDROID_LINT: ""
  trigger:
    include: "https://gitlab-templates.ddbuild.io/mobile/v25558398-8517309a/static-analysis.yml"
    strategy: depend

analysis:licenses:
  tags: [ "arch:amd64" ]
  image: $CI_IMAGE_DOCKER
  stage: analysis
  timeout: 30m
  script:
    - GRADLE_OPTS="-Xmx3072m" ./gradlew checkDependencyLicences --stacktrace --no-daemon

# Test

jvm-unit-test:
  stage: test
  tags: [ "arch:amd64" ]
  image: $CI_IMAGE_DOCKER
  timeout: 1h
  script:
    - rm -rf ~/.gradle/daemon/
    - export DD_AGENT_HOST="$BUILDENV_HOST_IP"
    - GRADLE_OPTS="-Xmx4096m" ./gradlew jvmUnitTestAll --no-daemon -Dorg.gradle.jvmargs=-javaagent:$DD_TRACER_FOLDER/dd-java-agent.jar=$DD_COMMON_AGENT_CONFIG
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit:
        - "**/build/test-results/testDebugUnitTest/*.xml"
        - "**/build/test-results/testReleaseUnitTest/*.xml"

sample-app-build-ios:
  stage: test
  tags: [ "macos:sonoma" ]
  timeout: 1h
  variables:
    BUILD_DESTINATION: "platform=iOS Simulator,name=iPhone 15 Pro Max,OS=17.4"
  script:
    # temporary workaround for RUM-4282
    - ./gradlew :dd-sdk-kotlin-multiplatform-core:podBuildDatadogObjcIphonesimulator
    - xcodebuild -project sample/iosApp/iosApp.xcodeproj -destination "$BUILD_DESTINATION" -scheme iosApp build | xcbeautify --preserve-unbeautified

sample-app-build-android:
  stage: test
  tags: [ "arch:amd64" ]
  image: $CI_IMAGE_DOCKER
  timeout: 1h
  script:
    - rm -rf ~/.gradle/daemon/
    - export DD_AGENT_HOST="$BUILDENV_HOST_IP"
    - GRADLE_OPTS="-Xmx4096m" ./gradlew :sample:androidApp:assembleDebug --no-daemon -Dorg.gradle.jvmargs=-javaagent:$DD_TRACER_FOLDER/dd-java-agent.jar=$DD_COMMON_AGENT_CONFIG
